### ISSUE TITLE
finish Chapter 29 Burger King example

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/SDM4inR#11]
BK<A8>_Double_Stacker   173     560     320     36      15      1       110     1040    29      1       7       30
BK<A8>_Triple_Stacker

A8 causes issues here in R at least (it's an umlaut?)  It seems like an error.

**Comment by deveaux69** [comment]
I know. Pain in the ass. I've spent hours cleaning these up. Guess there
are still issues and meat should be there. There are about 100 versions of
this data set. I'll have to go look.

**Comment by nicholasjhorton** [comment]
@sarahmcdonald20 can you please take a look at this?  Thanks in advance, Nick

**Comment by sarahmcdonald20** [comment]
Hi @nicholasjhorton ,

Am I checking to see whether 'meat' is part of the dataset? Everything seems to be running fine otherwise.

Thanks, 
Sarah

**Comment by nicholasjhorton** [comment]
Can you please confirm that the analysis in Chapter29.Rmd correctly reflects the material in the chapter?  If so, we are all set.  (I had thought that there were issues with the interaction model.)

> On Jun 13, 2018, at 10:12 AM, sarahmcdonald20 <notifications@github.com> wrote:
> 
> Hi @nicholasjhorton ,
> 
> Am I checking to see whether 'meat' is part of the dataset? Everything seems to be running fine otherwise.
> 
> Thanks,
> Sarah
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by sarahmcdonald20** [comment]
I checked the textbook in SMUDD and there is no hard copy of Chapter 29 to check with (it says its on the disk in the back of the book). Is there another location? There is a Burger King question at the end of Chapter 28, #27 on page 846. 
In terms of the interaction term, however, there does not seem to be an issue.

**Comment by nicholasjhorton** [comment]
I've added this at https://nhorton.people.amherst.edu/sdm4/SDM_04_Ch29.pdf

Can you please review this in detail to see if there are any discrepancies?

**Comment by sarahmcdonald20** [comment]
Thanks! 
I read through the chapter and the R chapter aligns with the topics in the (hardcopy) textbook, with the same outputs and discussions.

**Comment by nicholasjhorton** [comment]
Can you please remind me why: "Notice that the R2 of this final model is 0.689: this is different that in the book."  Is this a different model?  A different dataset?

**Comment by deveaux69** [comment]
Hi Nick,

I can’t tell if any of these are directed at me. I’ll assume not, unless otherwise instructed…

Thx,
Dick

**Comment by nicholasjhorton** [comment]
@sarahmcdonald20 I'm pretty lost in the presentation for section 29.3.  Can you please augment this with page refs and figure numbers as they exist?  Thanks in advance, Nick

**Comment by deveaux69** [comment]
Please add Paul to this thread too. Thx.

**Comment by nicholasjhorton** [comment]
Please note errors/updates I addressed in https://github.com/nicholasjhorton/SDM4inR/commit/281130656c28d251e7109a4f348d7468a3249164

**Comment by nicholasjhorton** [comment]
Finished via https://github.com/nicholasjhorton/SDM4inR/commit/7905aeb10c4e3da3bc265fb1b52868b1cbfba340
