### ISSUE TITLE
draft Chapter 27 (even more ANOVA!)

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/SDM4inR#15]

**Comment by wantpinow** [comment]
Hi Nick, I just added my first draft of 27 to the repo. I had an issue with the adjusted variable boxplots on pages 785 and 786. I hadn't seen them before so just followed what the book said. You can see from my boxplots that the shape of the plots are all right, its just the scale that is off. I couldn't seem to figure this one out

**Comment by nicholasjhorton** [comment]
Patrick F., I suspect that these are generated by controlling for the other factor.  Can you add an image/screenshot of what you got by running the analyses on your end?

Paul Velleman, might you be willing to take a look and advise?

Thanks in advance,

Nick

> On Jun 17, 2016, at 11:10 AM, Patrick Frenett notifications@github.com wrote:
> 
> Hi Nick, I just added my first draft of 27 to the repo. I had an issue with the adjusted variable boxplots on pages 785 and 786. I hadn't seen them before so just followed what the book said. You can see from my boxplots that the shape of the plots are all right, its just the scale that is off. I couldn't seem to figure this one out
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by wantpinow** [comment]
So for figure 27.2 on page 785, the boxplot on the right looks to have a range from ~2-7 inches, however mine in centered around 0 - even though when looking at it the shape is correct.

![fig27_2](https://cloud.githubusercontent.com/assets/19333670/16243765/d22f0cd4-37c6-11e6-8540-1d4c6cae77d5.png)

**Comment by nicholasjhorton** [comment]
Patrick, are there any updates regarding this issue?  Thanks in advance for any guidance.
