### ISSUE TITLE
website issue: links to www3 should be www (or preferably, relative)

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/SDM4inR#18]
Patrick F., can you please update the website source files so that the links are relative (not absolute). If that's not workable can you please change www3 to www?  Thanks in advance, Nick

**Comment by patrick714** [comment]
Hi Nick,

Can you be more specific about what links you are referring to?

I can bring this to the media team and see where we can fit this in.

Thank you,

Patrick

On Wed, Jun 15, 2016 at 10:03 AM, Nicholas Horton notifications@github.com
wrote:

> Patrick, can you please update the website source files so that the links
> are relative (not absolute). If that's not workable can you please change
> www3 to www? Thanks in advance, Nick
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nicholasjhorton/SDM4inR/issues/18, or mute the thread
> https://github.com/notifications/unsubscribe/AQ04oEzRpQjEPvy-eyfsRox6l8bsGLlyks5qMAYfgaJpZM4I2Y-i
> .

## 

_Patrick Barbera_
Acquisitions Editor, Statistics
patrick.barbera@pearson.com

_Pearson Always Learning_

## www.pearsonhighered.com

_Nothing ventured, nothing gained_

**Comment by nicholasjhorton** [comment]
Patrick B.: wrong Patrick (I assigned this to Patrick Frenett, aka "wantpinow"). I've edited the issue to make this clear and I'll be more careful in the future.  Sorry for the confusion, Nick

**Comment by patrick714** [comment]
Hi - oh ok, no problem

Whatever you are doing sounds interesting though

Have a good day!

On Wed, Jun 15, 2016 at 10:06 AM, Nicholas Horton notifications@github.com
wrote:

> Patrick B.: wrong Patrick (I assigned this to Patrick Frenett, aka
> "wantpinow"). I've edited the issue to make this clear and I'll be more
> careful in the future. Sorry for the confusion, Nick
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/nicholasjhorton/SDM4inR/issues/18#issuecomment-226197752,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQ04oIlF7aQtolJVe13lQaI4m8cWaxAOks5qMAcBgaJpZM4I2Y-i
> .

## 

_Patrick Barbera_
Acquisitions Editor, Statistics
patrick.barbera@pearson.com

_Pearson Always Learning_

## www.pearsonhighered.com

_Nothing ventured, nothing gained_

**Comment by wantpinow** [comment]
Nick,

If we are going the relative file route, should we include a copy of the Rmd and pdf files in the website folder so that they can be linked to locally? I can do that and link them up if need be

**Comment by nicholasjhorton** [comment]
I'd prefer to leave things as is (I just overlay the web files on top of the chapter files).

Nick

> On Jun 17, 2016, at 12:57 PM, Patrick Frenett notifications@github.com wrote:
> 
> Nick,
> 
> If we are going the relative file route, should we include a copy of the Rmd and pdf files in the website folder so that they can be linked to locally? I can do that and link them up if need be
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by patrick714** [comment]
Hi Nick,

This is coming together really nicely - very clean design and access
options.

Looks like a great resource!

Patrick

On Fri, Jun 17, 2016 at 1:39 PM, Nicholas Horton notifications@github.com
wrote:

> I'd prefer to leave things as is (I just overlay the web files on top of
> the chapter files).
> 
> Nick
> 
> > On Jun 17, 2016, at 12:57 PM, Patrick Frenett notifications@github.com
> > wrote:
> > 
> > Nick,
> > 
> > If we are going the relative file route, should we include a copy of the
> > Rmd and pdf files in the website folder so that they can be linked to
> > locally? I can do that and link them up if need be
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> Nicholas Horton
> Professor of Statistics
> Department of Mathematics and Statistics, Amherst College
> Box 2239, 31 Quadrangle Dr
> Amherst, MA 01002-5000
> https://www.amherst.edu/people/facstaff/nhorton
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/nicholasjhorton/SDM4inR/issues/18#issuecomment-226833678,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQ04oDWpA2eooOjHYxnzSSpTbJW6rfsbks5qMtvpgaJpZM4I2Y-i
> .

## 

_Patrick Barbera_
Acquisitions Editor, Statistics
patrick.barbera@pearson.com

_Pearson Always Learning_

## www.pearsonhighered.com

_Nothing ventured, nothing gained_

**Comment by nicholasjhorton** [comment]
Patrick, I see two copies of the files in the github repo: one in SDM4_Site/files and one in "chapter files".  Are these redundant?

**Comment by nicholasjhorton** [comment]
I moved the redundant "chapter files" into a folder called OLD.
