### ISSUE TITLE
Changes to SDM4

### ISSUE THREAD

**Issue by wantpinow** [nicholasjhorton/SDM4inR#19]
Summarizing the changes made in the last few weeks:

Added chapters 9, 10, 27.
Finished chapter 29.
Created site at amherst.edu/~nhorton/sdm4

**Comment by nicholasjhorton** [comment]
Done.  Patrick B., Dick, and/or Paul you may want to review at http://www.amherst.edu/~nhorton/sdm4

**Comment by patrick714** [comment]
Hi Nick,

This would be a great thing for us to promote with SDM - I wanted to
confirm that you were okay with that and also ask if it is ready to go.

R comes up alot and this kind of support and integration would be something
of interest.

Thank you,

Patrick

On Tue, Jun 28, 2016 at 10:44 PM, Nicholas Horton notifications@github.com
wrote:

> Done. Patrick B., Dick, and/or Paul you may want to review at
> http://www.amherst.edu/~nhorton/sdm4
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nicholasjhorton/SDM4inR/issues/19#issuecomment-229241970,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQ04oFw6zC-LgS9vH1N0sPSwFq-wv4JAks5qQdwcgaJpZM4I_tfB
> .

## 

_Patrick Barbera_
Acquisitions Editor, Statistics
patrick.barbera@pearson.com

_Pearson Always Learning_

## www.pearsonhighered.com

_Nothing ventured, nothing gained_

**Comment by nicholasjhorton** [comment]
From my vantage point these materials are ready for people to use.  The SDM4 files were substantially complete before the end of the semester and the IS4 files were prepared primarily by Patrick F.  That's not to say that there aren't minor typos or areas where they could be improved.

Nick

> On Jun 29, 2016, at 8:54 AM, patrick714 notifications@github.com wrote:
> 
> Hi Nick,
> 
> This would be a great thing for us to promote with SDM - I wanted to
> confirm that you were okay with that and also ask if it is ready to go.
> 
> R comes up alot and this kind of support and integration would be something
> of interest.
> 
> Thank you,
> 
> Patrick
> 
> On Tue, Jun 28, 2016 at 10:44 PM, Nicholas Horton notifications@github.com
> wrote:
> 
> > Done. Patrick B., Dick, and/or Paul you may want to review at
> > http://www.amherst.edu/~nhorton/sdm4
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/nicholasjhorton/SDM4inR/issues/19#issuecomment-229241970,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AQ04oFw6zC-LgS9vH1N0sPSwFq-wv4JAks5qQdwcgaJpZM4I_tfB
> > .
> 
> ## 
> 
> _Patrick Barbera_
> Acquisitions Editor, Statistics
> patrick.barbera@pearson.com
> 
> _Pearson Always Learning_
> 
> ## www.pearsonhighered.com
> 
> _Nothing ventured, nothing gained_
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
