### ISSUE TITLE
#LatticeChanges, no ggformula for boxplot yet?

### ISSUE THREAD

**Issue by sarahmcdonald20** [nicholasjhorton/SDM4inR#26]
In chapter 10. 

`require(mosaic)
require(knitr)

library(mosaic)
obs <- c(5,4,7,5,18,6,5,4,6) 
ID <- 1:length(data)
data <- data.frame(ID, obs)

gf_boxplot(~ obs, data = data)`

Produces:
Error: Invalid formula type for gf_boxplot.

**Comment by nicholasjhorton** [comment]
For now please just leave this as gf_boxplot(obs ~ 1, data = data)  and add a comment # gf_boxplot(~ age) to be added in the future
