### ISSUE TITLE
issue in chapter 24

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/SDM4inR#29]
mosaicplot() to be replaced by vcd::mosaic() to get better coloring.

**Comment by sarahmcdonald20** [comment]
Sorry about that! I realized I hadn't pushed the change!

**Comment by nicholasjhorton** [comment]
closed via https://github.com/nicholasjhorton/SDM4inR/commit/67eec861d597e2e32e8d4e3d627faded36fabeab
