### ISSUE TITLE
No website link available for ISP9?

### ISSUE THREAD

**Issue by sarahmcdonald20** [nicholasjhorton/SDM4inR#34]
commit: 50afb3422ec339ed84d51d9b3f4d87b92454f87f

Hi @nicholasjhorton , 

I can't seem to find a link to the ISP9 for a reference/hyperlink on the website under the 'Other Resources' tab. For now, I've left it without a hyperlink.

**Comment by nicholasjhorton** [comment]
All you need to do is replace sdm4 by ips9. 

All the best,

Nick
